spring:
  rabbitmq:
    host: 120.27.223.76
    port: 8465
    username: ywdz
    password: ywdz3.3test
    virtual-host: mqDocker76
    listener:
      simple:
        # 多消费者轮询模式
        prefetch: 1  #每个消费者都能收到的未被消费的最大消息数量
        # manual：手动，auto：自动
        # 设置消费端手动,返回分为：ack（无异常），nack（存在异常），reject（否定确认）
#        acknowledge-mode: manual
    # 确认消息已发送到交换机(Exchange)
    publisher-returns: true
    # 确认消息已发送到队列(Queue)
    publisher-confirm-type: correlated


